SET GLOBAL local_infile=1;

LOAD DATA LOCAL INFILE './seed_data/actor1.del' INTO TABLE MovieDB_actor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE './seed_data/actor2.del' INTO TABLE MovieDB_actor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE './seed_data/actor3.del' INTO TABLE MovieDB_actor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE './seed_data/director.del' INTO TABLE MovieDB_director FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE './seed_data/movie.del' INTO TABLE MovieDB_movie FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE './seed_data/movieactor1.del' INTO TABLE MovieDB_movieactor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE './seed_data/movieactor2.del' INTO TABLE MovieDB_movieactor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE './seed_data/moviedirector.del' INTO TABLE MovieDB_moviedirector FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE './seed_data/moviegenre.del' INTO TABLE MovieDB_moviegenre FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

 INSERT INTO MovieDB_MaxPersonID VALUES (69000);
 INSERT INTO MovieDB_MaxMovieID VALUES (4750);