SET GLOBAL local_infile = 'ON';

LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/actor1.csv' INTO TABLE Actors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/actor2.csv' INTO TABLE Actors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/actor3.csv' INTO TABLE Actors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/director.csv' INTO TABLE Directors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/movie.csv' INTO TABLE Movies FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/movieactor1.csv' INTO TABLE MovieActors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/movieactor2.csv' INTO TABLE MovieActors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/moviedirector.csv' INTO TABLE MovieDirectors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'MovieDB/sql/seed_data/csv/moviegenre.csv' INTO TABLE MovieGenres FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

SET FOREIGN_KEY_CHECKS = 1;
