# Generated by Django 6.1.1 on 2026-09-26 10:06

import django.db.models.deletion
import moviedb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Action', 'Action'), ('Adult', 'Adult'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Crime', 'Crime'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Short', 'Short'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], default='Drama', max_length=20, verbose_name='Genre Value')),
            ],
        ),
        migrations.CreateModel(
            name='MpaaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('NC-17', 'NC-17'), ('R', 'R'), ('PG-13', 'PG-13'), ('PG', 'PG'), ('G', 'G'), ('surrendered', 'Not Rated')], max_length=20, verbose_name='Mpaa Rating Value')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first', models.CharField(max_length=50, verbose_name='First Name')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Sex')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('dod', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Death')),
            ],
            options={
                'ordering': ['last', 'first'],
                'constraints': [models.CheckConstraint(condition=models.Q(('dod__isnull', True), ('dod__gte', models.F('dob')), _connector='OR'), name='actor_dod_gte_dob', violation_error_message='Date of death cannot be before date of birth.')],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=20, verbose_name='Last Name')),
                ('first', models.CharField(max_length=20, verbose_name='First Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('dod', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Death')),
            ],
            options={
                'ordering': ['last', 'first'],
                'constraints': [models.CheckConstraint(condition=models.Q(('dod__isnull', True), ('dod__gte', models.F('dob')), _connector='OR'), name='director_dod_gte_dob', violation_error_message='Date of death cannot be before date of birth.')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Movie Title')),
                ('year', models.IntegerField(default=moviedb.models.current_year, validators=[moviedb.models.validate_year], verbose_name='Year')),
                ('companies', models.ManyToManyField(to='moviedb.company')),
                ('directors', models.ManyToManyField(to='moviedb.director')),
                ('genres', models.ManyToManyField(to='moviedb.genre')),
            ],
            options={
                'ordering': ['title', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.actor', verbose_name='Actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.movie', verbose_name='Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(through='moviedb.MovieActor', to='moviedb.actor'),
        ),
        migrations.CreateModel(
            name='MovieActorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('movie_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.movieactor')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='mpaa_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moviedb.mpaarating', verbose_name='Mpaa Rating'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('user_name', models.CharField(max_length=20, verbose_name='User Name')),
                ('rating', models.IntegerField(choices=[(1, '1-star'), (2, '2-star'), (3, '3-star'), (4, '4-star'), (5, '5-star')], default=5, verbose_name='User Rating')),
                ('comment', models.TextField(blank=True, default='', max_length=2000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='moviedb.movie', verbose_name='Movie')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddConstraint(
            model_name='movieactor',
            constraint=models.UniqueConstraint(fields=('movie', 'actor'), name='unique_movie_actor'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'year'), name='unique_movie_title_year'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1800)), name='movie_year_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__range', (1, 5))), name='review_rating_1_to_5'),
        ),
    ]
