# Generated by Django 6.1.1 on 2026-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('moviedb', '0003_auto_20151123_1130'), ('moviedb', '0004_auto_20160821_0208'), ('moviedb', '0005_movie_year_callable_default'), ('moviedb', '0006_movie_unique_title_year')]

    dependencies = [
        ('moviedb', '0002_sprocs_seeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(through='moviedb.MovieActor', to='moviedb.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='companies',
            field=models.ManyToManyField(through='moviedb.MovieCompany', to='moviedb.company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(through='moviedb.MovieDirector', to='moviedb.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='moviedb.MovieGenre', to='moviedb.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Movie Title'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'year'), name='unique_movie_title_year'),
        ),
    ]
