# Generated by Django 6.1.1 on 2026-09-26 09:46

import moviedb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moviedb", "0003_auto_20151123_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="dod",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Date of Death"
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="dod",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Date of Death"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(
                default=moviedb.models.current_year,
                validators=[moviedb.models.validate_year],
                verbose_name="Year",
            ),
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dod__isnull", True),
                    ("dod__gte", models.F("dob")),
                    _connector="OR",
                ),
                name="actor_dod_gte_dob",
                violation_error_message="Date of death cannot be before date of birth.",
            ),
        ),
        migrations.AddConstraint(
            model_name="director",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dod__isnull", True),
                    ("dod__gte", models.F("dob")),
                    _connector="OR",
                ),
                name="director_dod_gte_dob",
                violation_error_message="Date of death cannot be before date of birth.",
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1800)), name="movie_year_gte_min"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__range", (1, 5))),
                name="review_rating_1_to_5",
            ),
        ),
    ]
