# Generated by Django 6.1.1 on 2026-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moviedb", "0004_add_check_constraints_and_year_validator"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="movieactor",
            constraint=models.UniqueConstraint(
                fields=("movie", "actor"), name="unique_movie_actor"
            ),
        ),
        migrations.AddConstraint(
            model_name="moviecompany",
            constraint=models.UniqueConstraint(
                fields=("movie", "company"), name="unique_movie_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="moviedirector",
            constraint=models.UniqueConstraint(
                fields=("movie", "director"), name="unique_movie_director"
            ),
        ),
        migrations.AddConstraint(
            model_name="moviegenre",
            constraint=models.UniqueConstraint(
                fields=("movie", "genre"), name="unique_movie_genre"
            ),
        ),
    ]
