# Generated by Django 5.2.17 on 2026-09-26 06:45

from django.db import migrations, models

import MovieDB.models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieDB", "0004_auto_20160821_0208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(
                default=MovieDB.models.current_year, verbose_name="Year"
            ),
        ),
    ]
