# Generated by Django 5.2.17 on 2026-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moviedb", "0005_movie_year_callable_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Movie Title"),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                fields=("title", "year"), name="unique_movie_title_year"
            ),
        ),
    ]
